### ISSUE TITLE
Proper effect constructing

### ISSUE THREAD

**Issue by Phill101** [Ledostuff/calories-counter#2]
Ты неправильно конструируешь эффекты. Например я увидел такое:

https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/repository/TranslationProductRepositoryHttpInterpreter.scala#L27-L29

**pure** - это функция, которая поднимает в контекст `F[_]` **чистое** значение, **уже вычисленное**. Нельзя сайд-эффекты типа `println` поднимать в контекст при помощи функции `pure`. Ты этим не откладываешь сайд-эффект - он исполнится не в момент интерпретации `IO`, но в момент его конструирования. 
Верный путь - использовать правильный конструктор сайд-эффектов. Для `IO` это например `apply`, а для `cats-effect` это `delay` из тайп-класса `Sync`.

А ещё лучше написать функциональную обёртку над логгером. Простенькую, которая правильным образом создаёт отложенные вычисления с логгированием. Тогда и в твоём классе не появится более широкий констрейнт на `F[_]` (останется `Monad`, а не `Sync`)

Вот ещё пример:
https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/Server.scala#L29

Что именно ты тут откладываешь? У тебя создание репозитория в этом случае не сайд-эффект. Для создания не нужно читать файловую систему, для создания не инициализируются никакие пулы, никакие переменные. Так ведь? Соответственно тут и откладывать ничего не нужно. Создание этого класса - не является сайд-эффектом.
Потому такие эффекты можно чейнить при помощи функции `map` ну или при помощи `=` в for-comprehension.

**Comment by Phill101** [comment]
Увидел, что логгер у тебя был всё это время.

https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/logging/Log.scala#L6-L9

 Тогда его нужно поправить и использовать в том репо

**Comment by Ledostuff** [comment]
PR is merged, close this issue.
