### ISSUE TITLE
Side-effect inside pure function

### ISSUE THREAD

**Issue by Phill101** [Ledostuff/calories-counter#3]
`foodService.getFood` - это сайд-эффект.

https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/repository/ProductCaloriesRepositoryHttpInterpreter.scala#L22

Его соответствено нужно "откладывать" в терминах систем-эффектов и затем чейнить при помощи `flatMap` а не `map`.

Обрати ещё внимание вот на что:
https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/repository/ProductCaloriesRepositoryHttpInterpreter.scala#L27-L31

Иногда ты очень вербозно пишешь. Я рекомендую задумываться над тем как сократить код, каждый раз когда ты его пишешь. Чем меньше букв, тем проще читать. Этот блок яркая иллюстрация. Его можно было бы записать просто
```scala
OptionT(Sync[F].delay(foodService.searchFoods(name)).fmap(getFoodInfoFunction))
```

**Comment by Phill101** [comment]
Получение времени - это сайд эффект

https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/services/ProductCaloriesService.scala#L32

**Comment by Ledostuff** [comment]
PR is merged, close this issue.
