### ISSUE TITLE
Just for you to know

### ISSUE THREAD

**Issue by Phill101** [Ledostuff/calories-counter#4]
https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/domain/database/ProductService.scala#L19

прямо с пакетом расширений для функтора, кроме `as`, приходит ещё функция `void` которая делает как раз `.as(())`

**Comment by Phill101** [comment]
https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/domain/database/Product.scala#L6

Я тебе не советую использовать `Seq`. Раньше (в чуть более древней скале) он и вовсе был опасным. Лучше всегда использовать конкретные типы коллекций везде где только можешь.
Это позволит по месту использования правильно рассуждать о типе коллекции, с которой нужно будет работать. Пользователь сможет сразу понимать какие операции могут быть дорогими, а какие нет.
Только представь чудесную ситуацию:
```scala
val seq: Seq[Int] = LazyList.from(1)
// or
// val seq: Seq[Int] = Stream.from(1)
```
По месту использования, по типу `Seq`, можно и не предположить, что коллекция бесконечная.

**Comment by Phill101** [comment]
https://github.com/Ledostuff/calories-counter/blob/71987d4faa86ffbf8f87d8176cdd9766855cdf84/src/main/scala/ru/ledostuff/calories/infrastructure/services/ProductCaloriesService.scala#L45-L48

намного проще воспринимается такая запись.
```scala
_ <- EitherT.liftF(log.info(s"search translation for name $name"))
translatedProductInfo <- EitherT.fromOptionF(translateService.translateProductName(name).value, TranslationNotFound)
```

старайся всегда упрощать насколько можешь

**Comment by Ledostuff** [comment]
@Phill101 PR is ready

**Comment by Ledostuff** [comment]
PR is merged, close this issue
